
export const BLOCK_MOVEMENT_NORTH_WEST = 0x1;
export const BLOCK_MOVEMENT_NORTH = 0x2;
export const BLOCK_MOVEMENT_NORTH_EAST = 0x4;
export const BLOCK_MOVEMENT_EAST = 0x8;
export const BLOCK_MOVEMENT_SOUTH_EAST = 0x10;
export const BLOCK_MOVEMENT_SOUTH = 0x20;
export const BLOCK_MOVEMENT_SOUTH_WEST = 0x40;
export const BLOCK_MOVEMENT_WEST = 0x80;

export const BLOCK_MOVEMENT_OBJECT = 0x100;
export const BLOCK_MOVEMENT_FLOOR_DECORATION = 0x40000;
export const BLOCK_MOVEMENT_FLOOR = 0x200000; // Eg. water
export const BLOCK_MOVEMENT_FULL = BLOCK_MOVEMENT_OBJECT | BLOCK_MOVEMENT_FLOOR_DECORATION | BLOCK_MOVEMENT_FLOOR;

export const BLOCK_LINE_OF_SIGHT_NORTH = BLOCK_MOVEMENT_NORTH << 9; // 0x400
export const BLOCK_LINE_OF_SIGHT_EAST = BLOCK_MOVEMENT_EAST << 9; // 0x1000
export const BLOCK_LINE_OF_SIGHT_SOUTH = BLOCK_MOVEMENT_SOUTH << 9; // 0x4000
export const BLOCK_LINE_OF_SIGHT_WEST = BLOCK_MOVEMENT_WEST << 9; // 0x10000
export const BLOCK_LINE_OF_SIGHT_FULL = 0x20000;
